version: "3"
services:
  app:
    image: nginx:latest
    container_name: "app"
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    extra_hosts:
      - "local_dev:192.168.0.163"
